// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ogQ2a6zk4JVUThXtpfYcPRBZ-2i-_5g',
    appId: '1:1039570206588:web:965d830cf5c2b5b41caef9',
    messagingSenderId: '1039570206588',
    projectId: 'aquaanalyst-ai',
    authDomain: 'aquaanalyst-ai.firebaseapp.com',
    storageBucket: 'aquaanalyst-ai.firebasestorage.app',
    measurementId: 'G-QM7JB5QEKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JRFbYtoAAVKXDwiARZzHV9837un8r4U',
    appId: '1:1039570206588:android:4ee6e6544b9b5cc31caef9',
    messagingSenderId: '1039570206588',
    projectId: 'aquaanalyst-ai',
    storageBucket: 'aquaanalyst-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFmCi7nd8aOyQUdD-VEJpKAt64y5fZsLA',
    appId: '1:1039570206588:ios:21993be90fd982211caef9',
    messagingSenderId: '1039570206588',
    projectId: 'aquaanalyst-ai',
    storageBucket: 'aquaanalyst-ai.firebasestorage.app',
    iosBundleId: 'com.example.aquaanalystAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFmCi7nd8aOyQUdD-VEJpKAt64y5fZsLA',
    appId: '1:1039570206588:ios:21993be90fd982211caef9',
    messagingSenderId: '1039570206588',
    projectId: 'aquaanalyst-ai',
    storageBucket: 'aquaanalyst-ai.firebasestorage.app',
    iosBundleId: 'com.example.aquaanalystAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ogQ2a6zk4JVUThXtpfYcPRBZ-2i-_5g',
    appId: '1:1039570206588:web:36f69eb9489bf82a1caef9',
    messagingSenderId: '1039570206588',
    projectId: 'aquaanalyst-ai',
    authDomain: 'aquaanalyst-ai.firebaseapp.com',
    storageBucket: 'aquaanalyst-ai.firebasestorage.app',
    measurementId: 'G-CV20QN67PY',
  );
}
